### ISSUE TITLE
ALBでホスト名ベースでルーティングする

### ISSUE THREAD

**Issue by tmonj1** [tmonj1/memorandom#8]
## Key points

* ALB (AWS LBC) はデフォルトですべての namespace を watch するようになっている。`--watch-namespace` オプションは気にする必要はない (このオプションは逆に namespace を限定するときに使う)
* 複数のルールを一つのALBに集約するには `group.name` を同じにする
* ingress はどの namespace にデプロイしてもよいが、`.spec.rules[].http.paths[].path.backend.service.name`を指定するとき、ホスト名だけ指定すると ingress と同一 namespace で補完される。ingress と別 namespace にルーティングしたいときは、`my-service.test2.svc.cluster.local` のようにFQDNで指定する必要がある。
* 最後にデフォルトのルールをマッチさせるには、そのルールの `alb.ingress.kubernetes.io/group.order` を 999 に設定すればよさそう (出典: https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/alb-ingress.html)

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: shared-alb # すべてこの名前で統一する
    alb.ingress.kubernetes.io/group.order: "900"   # 0〜1000。0が最優先。
spec:
  rules:
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: default
            port:
              number: 80
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  namespace: test2
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: shared-alb
spec:
  rules:
  - host: test1.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: test1-service
            port:
              number: 80
```
